---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/immich
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: local-path-provisioner
    - name: cloudnative-pg
    - name: tailscale-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/homepage
  prune: true
  wait: true
  dependsOn:
    - name: tailscale-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatus
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/gatus
  prune: true
  wait: true
  dependsOn:
    - name: tailscale-operator
    - name: local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
