apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - b2.sops.yaml
  - restic-cache.yaml
  - cronjob.yaml
  - ocirepository.yaml
  - backrest-seed.yaml
  - backrest.yaml
