apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - grafana-admin.sops.yaml
  - alertmanager-telegram.sops.yaml
  - alertmanager-healthchecks.sops.yaml
  - helmrelease.yaml
  - homelab-alerts.yaml
