apiVersion: ENC[AES256_GCM,data:HAU=,iv:BWHsObpvgCpOIvddbZ3622gO6tAvBCxjYDlBWOOYed4=,tag:WAYNwQffb7cvxoqpLCquMQ==,type:str]
kind: ENC[AES256_GCM,data:5FPNOUW1,iv:TKq6+RdHFEDzzL91qhl9Vt0F/eQdOUiamHwOC7j33n0=,tag:SN1zs6n5kAeOk6hfC9p47A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4+gPzk+qfKbVj2kL5sI=,iv:tOgvjGQY0kr+psAJpa2ZR8xpukOJqsa8KAyXgdSc3PA=,tag:mCY+nEnl0PGn9H1XxBcsJA==,type:str]
    namespace: ENC[AES256_GCM,data:pZyso91ogWhV,iv:CQRSTj/imPyvoXEb4klEb0Tr8G0zUkNvNaUFC1UrCoY=,tag:lOdbiKbvXLAD3FAg0kaPJQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:cLo+/jRlGQbb5HJjAlBS6TE=,iv:SHMrxJefAtYWetMDDZoJAmEdIgaSUrfjNVGnVz4dMMI=,tag:RHmmBByO2WsNy040jbkyNw==,type:str]
    client_secret: ENC[AES256_GCM,data:Rf+ZYdzfFaA5GF03IWDArM7hOFfjva+A2kwhna1loknlMXYfvsBI1NuxDj3P0bw1VbYHo7UpViGCgXuy9u5JcA==,iv:3e1lTPB94OMW7WPqc4OHYrP7Z7PKBCHsDq7nyCA99N0=,tag:1KhK2Kqbm2hiIVsxlYLmLg==,type:str]
sops:
    age:
        - recipient: age1lpesjq3srcaw2hy5kymumr833eere02y8qqrpnne4wphcaklkdaqwujk7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUGxEdStHdVYzNytPcDdV
            RkNEZ0pVbTBCTDVyMVgwTk9QVmlPVE51eFF3CjVjQTU1VzJjZjZiQkp3UTE1RW9E
            cldYSEdOOG9rTC9wMVRqSHVVRGZaTHcKLS0tIElSQWpMa0lrRW12c2FwQTBDdVR3
            aGUwaDc3NnFUUE9ld3ZQYWduaGl2OEUK+Dk3y34dSPc7OczLnsyvxaWcszOyhqa0
            zGRGeR9Ib8lJSXpN8MD9fCaQ8E10ZVhf0esieToyWp/iN9zhbts+Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T12:23:10Z"
    mac: ENC[AES256_GCM,data:XGeBMErlDfs6JwpUt7gHOu0Rr64+CzkRgOxKcEjwfLi+es54sgzdbGOaMYN+rb43fNM+0REUp2KZLIDhC+fcHhZLAum2Kz1DYvexrffHHdz8NVXEd8MC4lXCTj5iiUNPyi9Vy/63alPpri691eNEOm1cqpAe/NYw1da7uououCM=,iv:KB7ev8Jrgus6rEmuBk0BsqRsH8vQFZc9LopgalBeQIY=,tag:ezkPqHJaLHVJXCYtjJjMyQ==,type:str]
    pgp:
        - created_at: "2026-09-18T12:23:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dp/riva+aomESAQdA68L5eXpvg0T8lWksZfY/E5M+tVeggx49spBVnetVNSIw
            KZ4MO32SpEeKCPkA7x2M4yjRBd9Ifk+L6oE7mKCAGfRtfESHUjMiEXguE/oq1tgT
            1GgBCQIQ9qXzwwWTGsiK0U3IhLrqYCBez+5svt3OgvGN7i13gJLfLpxj2VSj/OaU
            NfPg+TkSJXqlTEkUrEb1ZWTowRPCuYVuxcczWAzRSkis9u5vfTNOt9PqlNRA7jAG
            iRPi7EBDeUciog==
            =n5Pt
            -----END PGP MESSAGE-----
          fp: 412E958B884EF1D42A7AD3D4245301B551E25D5E
    unencrypted_suffix: _unencrypted
    version: 3.12.2
